# Generated by Django 5.0.6 on 2024-10-18 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('perticulers', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
                ('other', models.CharField(default=' ', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('perticulers', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
                ('other', models.CharField(default=' ', max_length=255)),
            ],
        ),
    ]
