# Generated by Django 5.0.6 on 2024-10-22 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0002_expence_bill_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expence',
            name='other',
            field=models.CharField(blank=True, default=' ', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='other',
            field=models.CharField(blank=True, default=' ', max_length=255, null=True),
        ),
    ]
