# Generated by Django 5.0.6 on 2024-10-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0003_alter_expence_other_alter_income_other'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='bill_number',
            field=models.CharField(default='No Bill', max_length=20),
        ),
    ]
