# Generated by Django 5.0.6 on 2025-08-19 03:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodlog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailylog',
            name='admin_comment',
        ),
        migrations.RemoveField(
            model_name='dailylog',
            name='comment_date',
        ),
        migrations.RemoveField(
            model_name='dailylog',
            name='commented_by',
        ),
        migrations.RemoveField(
            model_name='dailylog',
            name='food_image',
        ),
        migrations.RemoveField(
            model_name='dailylog',
            name='meals_consumed',
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='notes',
            field=models.TextField(blank=True, help_text='General notes for the day', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='weight',
            field=models.FloatField(blank=True, help_text='Weight in kg', null=True),
        ),
        migrations.CreateModel(
            name='MealEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack_morning', 'Morning Snack'), ('snack_afternoon', 'Afternoon Snack'), ('snack_evening', 'Evening Snack'), ('other', 'Other')], max_length=20)),
                ('meal_description', models.TextField(help_text='Description of meal consumed', max_length=1000)),
                ('food_image', models.FileField(blank=True, null=True, upload_to='meal_images/')),
                ('custom_meal_name', models.CharField(blank=True, help_text="If 'Other' is selected", max_length=100, null=True)),
                ('calories_estimate', models.IntegerField(blank=True, help_text='Estimated calories (optional)', null=True)),
                ('time_consumed', models.TimeField(blank=True, help_text='Time when meal was consumed', null=True)),
                ('admin_comment', models.TextField(blank=True, help_text='Admin feedback', max_length=1000, null=True)),
                ('comment_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commented_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('daily_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='foodlog.dailylog')),
            ],
            options={
                'ordering': ['time_consumed', 'created_at'],
            },
        ),
    ]
