# Generated by Django 5.0.6 on 2025-08-18 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnquiryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=250)),
                ('phone_number', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('number_of_followup', models.IntegerField(default=0)),
                ('last_follow_up_date', models.DateField(blank=True, null=True)),
                ('next_follow_up_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('in_progress', 'In Progress'), ('not_required', 'Not Required'), ('rejected', 'rejected')], default='pending', max_length=30)),
                ('conversion', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EnquiryStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_status', models.DateField(auto_now_add=True)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('in_progress', 'In Progress'), ('not_required', 'Not Required'), ('rejected', 'rejected')], default='pending', max_length=30)),
                ('call_status', models.CharField(choices=[('rnr', 'RNR'), ('callback', 'Callback'), ('interested', 'Interested'), ('not_interested', 'Not Interested'), ('converted', 'Converted'), ('follow_up', 'Follow Up'), ('closed', 'Closed')], default='rnr', max_length=30)),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enquiry.enquirydata')),
            ],
        ),
    ]
