# Generated by Django 5.0.6 on 2025-08-18 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquirystatus',
            name='date_of_status',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
