# Generated by Django 3.2.23 on 2023-12-08 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigarationDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JWT_IP', models.CharField(max_length=255)),
                ('Call_Back_IP', models.CharField(max_length=255)),
                ('Admin_Username', models.CharField(max_length=255)),
                ('Admin_Password', models.CharField(max_length=255)),
            ],
        ),
    ]
