# Generated by Django 3.2.23 on 2023-12-08 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configarationdb',
            name='Call_Back_Port',
            field=models.CharField(default=20, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configarationdb',
            name='JWT_PORT',
            field=models.CharField(default=80, max_length=11),
            preserve_default=False,
        ),
    ]
