# Generated by Django 4.2.7 on 2023-12-21 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0003_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('Quary', models.TextField(max_length=2000)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
