# Generated by Django 3.2.14 on 2023-11-30 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberdata',
            name='Access_Token_Id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
