# Generated by Django 3.2.14 on 2023-12-04 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0003_auto_20231130_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='Amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
