# Generated by Django 3.2.14 on 2023-12-04 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0004_alter_payment_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToGate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Validity_Date', models.DateField()),
                ('Status', models.BooleanField(default=False)),
                ('Member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Members.memberdata')),
                ('Subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Members.subscription')),
            ],
        ),
    ]
