# Generated by Django 3.2.14 on 2023-12-04 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0005_accesstogate'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesstogate',
            name='Payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
