# Generated by Django 4.2.7 on 2023-12-20 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0007_payment_mode_of_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Discount_Percentage', models.FloatField()),
                ('Till_Date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='memberdata',
            name='Discount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
