# Generated by Django 4.2.7 on 2023-12-20 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0008_discounts_memberdata_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberdata',
            name='Special_Discount',
            field=models.BooleanField(default=False),
        ),
    ]
