# Generated by Django 4.2.7 on 2023-12-20 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0009_memberdata_special_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberdata',
            name='Id_Upload',
            field=models.FileField(blank=True, null=True, upload_to='member_id'),
        ),
    ]
