# Generated by Django 4.2.7 on 2023-12-21 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0010_memberdata_id_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='Payment_Balance',
            field=models.FloatField(default=0),
        ),
    ]
