# Generated by Django 5.0.6 on 2024-06-11 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0011_payment_payment_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription_period',
            name='Category',
            field=models.CharField(choices=[('Day', 'Day'), ('Week', 'Week'), ('Month', 'Month'), ('Year', 'Year')], max_length=255),
        ),
    ]
