# Generated by Django 5.0.6 on 2024-06-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0012_alter_subscription_period_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberdata',
            name='Mobile_Number',
            field=models.CharField(max_length=255),
        ),
    ]
