# Generated by Django 5.0.6 on 2025-03-21 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0013_alter_memberdata_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='Member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Member_subscription', to='Members.memberdata'),
        ),
    ]
