# Generated by Django 5.0.6 on 2025-03-22 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0014_alter_subscription_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='Subscription_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Subscription_payment', to='Members.subscription'),
        ),
        migrations.CreateModel(
            name='BalancePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.FloatField()),
                ('Payment_Date', models.DateField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Members.payment')),
            ],
        ),
    ]
