# Generated by Django 5.0.6 on 2025-03-22 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0015_alter_payment_subscription_id_balancepayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancepayment',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_payment', to='Members.payment'),
        ),
    ]
