# Generated by Django 5.0.6 on 2025-04-04 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0016_alter_balancepayment_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='partial_payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='partial_payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='memberdata',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='Batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_time', to='Members.batch_db'),
        ),
    ]
