# Generated by Django 5.0.6 on 2025-04-04 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0017_payment_partial_payment_subscription_partial_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberdata',
            name='Address',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='memberdata',
            name='Date_Of_Birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='memberdata',
            name='Gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=255),
        ),
        migrations.AlterField(
            model_name='memberdata',
            name='Last_Name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='memberdata',
            name='Photo',
            field=models.FileField(blank=True, null=True, upload_to='member_photo'),
        ),
    ]
