# Generated by Django 5.0.6 on 2025-08-22 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0019_termsandconditions_gymmembership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymmembership',
            name='terms_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Members.termsandconditions'),
        ),
    ]
