# Generated by Django 5.0.6 on 2025-08-22 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0020_alter_gymmembership_terms_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymmembership',
            name='is_member',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gymmembership',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Members.memberdata'),
        ),
    ]
