# Generated by Django 5.0.6 on 2025-08-26 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0021_gymmembership_is_member_gymmembership_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymmembership',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrolment_form', to='Members.memberdata'),
        ),
    ]
