# Generated by Django 5.0.6 on 2025-09-15 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0024_memberdata_trainer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParqForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('emergency_contact_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('heart_condition', models.BooleanField(default=False, help_text='Has your doctor ever said that you have a heart condition?')),
                ('chest_pain_activity', models.BooleanField(default=False, help_text='Do you have chest pain brought on by physical activity?')),
                ('chest_pain_last_month', models.BooleanField(default=False, help_text='Have you developed chest pain in the last month?')),
                ('lose_consciousness', models.BooleanField(default=False, help_text='Do you tend to lose consciousness or fall over as a result of dizziness?')),
                ('bone_joint_problem', models.BooleanField(default=False, help_text='Do you have a bone or joint problem that could be aggravated by physical activity?')),
                ('medical_conditions', models.BooleanField(default=False, help_text='Do you suffer from asthma, diabetes, high blood pressure, epilepsy or a heart condition?')),
                ('medical_conditions_specify', models.TextField(blank=True, help_text='Please specify medical conditions', null=True)),
                ('current_treatment', models.BooleanField(default=False, help_text='Do you have any current conditions or injuries being treated by a doctor?')),
                ('current_treatment_specify', models.TextField(blank=True, help_text='Please specify current treatment', null=True)),
                ('other_reason', models.BooleanField(default=False, help_text='Do you know of any other reason why you should not take part in exercise?')),
                ('other_reason_specify', models.TextField(blank=True, help_text='Please specify other reasons', null=True)),
                ('participant_signature', models.TextField(blank=True, help_text='Participant signature data (base64)', null=True)),
                ('parent_guardian_signature', models.TextField(blank=True, help_text='Parent/Guardian signature data (base64)', null=True)),
                ('tutor_signature', models.TextField(blank=True, help_text='Tutor signature data (base64)', null=True)),
                ('form_date', models.DateField(auto_now_add=True)),
                ('participant_signature_date', models.DateField(blank=True, null=True)),
                ('parent_guardian_signature_date', models.DateField(blank=True, null=True)),
                ('tutor_signature_date', models.DateField(blank=True, null=True)),
                ('requires_doctor_consent', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_history_parque', to='Members.memberdata')),
            ],
            options={
                'verbose_name': 'PAR-Q Form',
                'verbose_name_plural': 'PAR-Q Forms',
            },
        ),
    ]
