# Generated by Django 5.0.6 on 2025-09-15 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0025_parqform'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthhistory',
            name='has_risky_health_conditions',
            field=models.BooleanField(default=False, help_text='Respiratory issues, joint problems, metabolic conditions, neurological disorders, etc.'),
        ),
        migrations.AddField(
            model_name='healthhistory',
            name='has_risky_heart_conditions',
            field=models.BooleanField(default=False, help_text='Heart disease, uncontrolled high blood pressure, irregular heartbeat, history of heart attack/stroke'),
        ),
        migrations.AddField(
            model_name='healthhistory',
            name='risky_health_conditions_details',
            field=models.TextField(blank=True, help_text='Explain specific health conditions that may be risky for gym workouts', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='healthhistory',
            name='risky_heart_conditions_details',
            field=models.TextField(blank=True, help_text='Explain specific heart/cardiovascular conditions', max_length=1000, null=True),
        ),
    ]
