# Generated by Django 5.0.6 on 2025-09-15 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0026_healthhistory_has_risky_health_conditions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberdata',
            name='risk_medical',
            field=models.BooleanField(default=False),
        ),
    ]
